apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: foos.controller.k8s.io
spec:
  group: controller.k8s.io
  names:
    kind: Foo
    plural: foos
    singular: foo
    shortNames:
      - foo
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: interger
                  minimum: 1
                  maximum: 10
