# https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html


check:
	ansible-playbook -i inventories/prd/host.ini task.yml --syntax-check

deploy:
	ansible-playbook -i inventories/prd/host.ini task.yml

361:
	ansible-playbook -i 361.ini task.yml
