

[server]
data-path = "./raft/data"
log-path = "./raft/logs"
log-level = "debug"

[cluster]
[[cluster.nodes]]
node-id=1
host="127.0.0.1"
http-port=7771
heartbeat-port=7772
replicate-port=7773

[[cluster.nodes]]
node-id=2
host="127.0.0.1"
http-port=8881
heartbeat-port=8882
replicate-port=8883

[[cluster.nodes]]
node-id=3
host="127.0.0.1"
http-port=9991
heartbeat-port=9992
replicate-port=9993
