# permissions for end users to view lvspods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lvspod-viewer-role
rules:
- apiGroups:
  - batch.lx1036.kubebuilder
  resources:
  - lvspods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.lx1036.kubebuilder
  resources:
  - lvspods/status
  verbs:
  - get
