/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

// BgpConfListerExpansion allows custom methods to be added to
// BgpConfLister.
type BgpConfListerExpansion interface{}

// BgpConfNamespaceListerExpansion allows custom methods to be added to
// BgpConfNamespaceLister.
type BgpConfNamespaceListerExpansion interface{}

// BgpPeerListerExpansion allows custom methods to be added to
// BgpPeerLister.
type BgpPeerListerExpansion interface{}

// EipListerExpansion allows custom methods to be added to
// EipLister.
type EipListerExpansion interface{}

// EipNamespaceListerExpansion allows custom methods to be added to
// EipNamespaceLister.
type EipNamespaceListerExpansion interface{}

// IPPoolListerExpansion allows custom methods to be added to
// IPPoolLister.
type IPPoolListerExpansion interface{}
