
version: '3.7'

networks:
  backend:
    driver: 'bridge'

services:
  toran-proxy:
    build:
      context: .
    ports:
      - "8080:80"
    networks:
      - backend
    volumes:
      - ~/.docker/toran-proxy-3:/data/toran-proxy
      - ~/.docker/toran-proxy-3/ssh:/data/toran-proxy/ssh
    environment:
      - TORAN_CRON_TIMER=minutes
      - TORAN_HTTPS=false
      - TORAN_REVERSE=false
      - TORAN_AUTH_ENABLE=false
      - TORAN_AUTH_USER='admin'
      - TORAN_AUTH_PASSWORD='password'
      - TORAN_TOKEN_GITHUB=${TORAN_TOKEN_GITHUB}
