# permissions for end users to edit lvspods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lvspod-editor-role
rules:
- apiGroups:
  - batch.lx1036.kubebuilder
  resources:
  - lvspods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.lx1036.kubebuilder
  resources:
  - lvspods/status
  verbs:
  - get
