// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || amd64p32 || arm || arm64 || loong64 || mips64le || mips64p32le || mipsle || ppc64le || riscv64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

// bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	AccessCtxSk                *ebpf.ProgramSpec `ebpf:"access_ctx_sk"`
	CtxNarrowAccess            *ebpf.ProgramSpec `ebpf:"ctx_narrow_access"`
	LookupDrop                 *ebpf.ProgramSpec `ebpf:"lookup_drop"`
	LookupPass                 *ebpf.ProgramSpec `ebpf:"lookup_pass"`
	MultiProgDrop1             *ebpf.ProgramSpec `ebpf:"multi_prog_drop1"`
	MultiProgDrop2             *ebpf.ProgramSpec `ebpf:"multi_prog_drop2"`
	MultiProgPass1             *ebpf.ProgramSpec `ebpf:"multi_prog_pass1"`
	MultiProgPass2             *ebpf.ProgramSpec `ebpf:"multi_prog_pass2"`
	MultiProgRedir1            *ebpf.ProgramSpec `ebpf:"multi_prog_redir1"`
	MultiProgRedir2            *ebpf.ProgramSpec `ebpf:"multi_prog_redir2"`
	RedirIp                    *ebpf.ProgramSpec `ebpf:"redir_ip"`
	RedirPort                  *ebpf.ProgramSpec `ebpf:"redir_port"`
	ReuseportDrop              *ebpf.ProgramSpec `ebpf:"reuseport_drop"`
	ReuseportPass              *ebpf.ProgramSpec `ebpf:"reuseport_pass"`
	SelectSockA                *ebpf.ProgramSpec `ebpf:"select_sock_a"`
	SelectSockA_noReuseport    *ebpf.ProgramSpec `ebpf:"select_sock_a_no_reuseport"`
	SelectSockB                *ebpf.ProgramSpec `ebpf:"select_sock_b"`
	SkAssignEexist             *ebpf.ProgramSpec `ebpf:"sk_assign_eexist"`
	SkAssignEstabsocknosupport *ebpf.ProgramSpec `ebpf:"sk_assign_estabsocknosupport"`
	SkAssignNull               *ebpf.ProgramSpec `ebpf:"sk_assign_null"`
	SkAssignReplaceFlag        *ebpf.ProgramSpec `ebpf:"sk_assign_replace_flag"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	RedirMap *ebpf.MapSpec `ebpf:"redir_map"`
	RunMap   *ebpf.MapSpec `ebpf:"run_map"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	RedirMap *ebpf.Map `ebpf:"redir_map"`
	RunMap   *ebpf.Map `ebpf:"run_map"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.RedirMap,
		m.RunMap,
	)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	AccessCtxSk                *ebpf.Program `ebpf:"access_ctx_sk"`
	CtxNarrowAccess            *ebpf.Program `ebpf:"ctx_narrow_access"`
	LookupDrop                 *ebpf.Program `ebpf:"lookup_drop"`
	LookupPass                 *ebpf.Program `ebpf:"lookup_pass"`
	MultiProgDrop1             *ebpf.Program `ebpf:"multi_prog_drop1"`
	MultiProgDrop2             *ebpf.Program `ebpf:"multi_prog_drop2"`
	MultiProgPass1             *ebpf.Program `ebpf:"multi_prog_pass1"`
	MultiProgPass2             *ebpf.Program `ebpf:"multi_prog_pass2"`
	MultiProgRedir1            *ebpf.Program `ebpf:"multi_prog_redir1"`
	MultiProgRedir2            *ebpf.Program `ebpf:"multi_prog_redir2"`
	RedirIp                    *ebpf.Program `ebpf:"redir_ip"`
	RedirPort                  *ebpf.Program `ebpf:"redir_port"`
	ReuseportDrop              *ebpf.Program `ebpf:"reuseport_drop"`
	ReuseportPass              *ebpf.Program `ebpf:"reuseport_pass"`
	SelectSockA                *ebpf.Program `ebpf:"select_sock_a"`
	SelectSockA_noReuseport    *ebpf.Program `ebpf:"select_sock_a_no_reuseport"`
	SelectSockB                *ebpf.Program `ebpf:"select_sock_b"`
	SkAssignEexist             *ebpf.Program `ebpf:"sk_assign_eexist"`
	SkAssignEstabsocknosupport *ebpf.Program `ebpf:"sk_assign_estabsocknosupport"`
	SkAssignNull               *ebpf.Program `ebpf:"sk_assign_null"`
	SkAssignReplaceFlag        *ebpf.Program `ebpf:"sk_assign_replace_flag"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.AccessCtxSk,
		p.CtxNarrowAccess,
		p.LookupDrop,
		p.LookupPass,
		p.MultiProgDrop1,
		p.MultiProgDrop2,
		p.MultiProgPass1,
		p.MultiProgPass2,
		p.MultiProgRedir1,
		p.MultiProgRedir2,
		p.RedirIp,
		p.RedirPort,
		p.ReuseportDrop,
		p.ReuseportPass,
		p.SelectSockA,
		p.SelectSockA_noReuseport,
		p.SelectSockB,
		p.SkAssignEexist,
		p.SkAssignEstabsocknosupport,
		p.SkAssignNull,
		p.SkAssignReplaceFlag,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel.o
var _BpfBytes []byte
