/*
Copyright 2021 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	bgplbk9siov1 "k8s-lx1036/k8s/network/bgplb/pkg/apis/bgplb.k9s.io/v1"
	versioned "k8s-lx1036/k8s/network/bgplb/pkg/client/clientset/versioned"
	internalinterfaces "k8s-lx1036/k8s/network/bgplb/pkg/client/informers/externalversions/internalinterfaces"
	v1 "k8s-lx1036/k8s/network/bgplb/pkg/client/listers/bgplb.k9s.io/v1"
	time "time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// BgpConfInformer provides access to a shared informer and lister for
// BgpConves.
type BgpConfInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.BgpConfLister
}

type bgpConfInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewBgpConfInformer constructs a new informer for BgpConf type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewBgpConfInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredBgpConfInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredBgpConfInformer constructs a new informer for BgpConf type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredBgpConfInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BgplbV1().BgpConves(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BgplbV1().BgpConves(namespace).Watch(context.TODO(), options)
			},
		},
		&bgplbk9siov1.BgpConf{},
		resyncPeriod,
		indexers,
	)
}

func (f *bgpConfInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredBgpConfInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *bgpConfInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&bgplbk9siov1.BgpConf{}, f.defaultInformer)
}

func (f *bgpConfInformer) Lister() v1.BgpConfLister {
	return v1.NewBgpConfLister(f.Informer().GetIndexer())
}
