---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: replicaset-pod
  labels:
    app: replicaset-pod
    restartCount: test
    log-filebeat: filebeat
  annotations:
    lx1036/controller-kind: filebeat
spec:
  replicas: 2
  template:
    metadata:
      name: replicaset-pod
      labels:
        app: replicaset-pod
    spec:
      containers:
        - name: replicaset-pod
          image: nginx:1.17.8
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              port: 80
              path: /index.html # /status(会不断重启), /index.html(正确的) 测试 RestartCount
            failureThreshold: 10
            initialDelaySeconds: 10
            periodSeconds: 10
      restartPolicy: Always
  selector:
    matchLabels:
      app: replicaset-pod
---
apiVersion: v1
kind: Service
metadata:
  name: replicaset-pod
spec:
  selector:
    app: replicaset-pod
  ports:
    - port: 8089
      targetPort: 80
      protocol: TCP
  type: NodePort
