

# https://github.com/AliyunContainerService/kube-eventer/blob/master/README.md

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-eventer
  labels:
    app: kube-eventer
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      name: kube-eventer
      labels:
        app: kube-eventer
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: kube-eventer
          image: registry.aliyuncs.com/acs/kube-eventer-amd64:v1.1.0-c93a835-aliyun
          imagePullPolicy: IfNotPresent
          command:
            - "/kube-eventer"
            - "--source=kubernetes:https://kubernetes.default"
            - --sink=dingtalk:https://oapi.dingtalk.com/robot/send?access_token=0be2c5f8f0e7d5408690aa934915b3de856341256d8ea9ef4ea8f8298a85328c&label=c281ada621585453b8da87bb2b4a51321&level=Normal
          env:
            - name: TZ
              value: "Asia/Shanghai"
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
              readOnly: true
            - mountPath: /usr/share/zoneinfo
              name: zoneinfo
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 250Mi
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: zoneinfo
          hostPath:
            path: /usr/share/zoneinfo
      restartPolicy: Always
  selector:
    matchLabels:
      app: kube-eventer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-eventer
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ""
    resources:
      - events
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-eventer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-eventer
subjects:
  - kind: ServiceAccount
    name: kube-eventer
    namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-system
  name: kube-eventer

