

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: etcd-operator
  namespace: etcd-operator
rules:
  - apiGroups:
      - etcd.database.coreos.com
    resources:
      - etcdclusters
      - etcdbackups
      - etcdrestores
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - "*"
  # The following permissions can be removed if not using S3 backup and TLS
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: etcd-operator
rules:
  - apiGroups:
      - etcd.database.coreos.com
    resources:
      - etcdclusters
      - etcdbackups
      - etcdrestores
    verbs:
      - "*"
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - "*"
  # The following permissions can be removed if not using S3 backup and TLS
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: etcd-operator
  namespace: etcd-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: etcd-operator
subjects:
  - kind: ServiceAccount
    name: default
    namespace: etcd-operator

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: etcd-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: etcd-operator
subjects:
  - kind: ServiceAccount
    name: default
    namespace: etcd-operator
