


# @see https://github.com/containerd/containerd/blob/main/docs/cri/config.md


disabled_plugins = []
imports = []
plugin_dir = ""
required_plugins = []

#root = "/var/lib/containerd" # docker 自带的 containerd 默认这个目录
# 如果是 /data 目录，可以使用 snapshotter = "overlayfs", /data 目录已经格式化完成，
# 如果是 /var/lib/containerd 必须是 native
root = "/data/containerd"

state = "/run/containerd"
version = 2
oom_score = -996

[plugins]
  [plugins."io.containerd.grpc.v1.cri"]
    sandbox_image = "https://r.harbor.cn/rancher/pause:3.2"
    [plugins."io.containerd.grpc.v1.cri".containerd]
      snapshotter = "overlayfs" # 默认
      #snapshotter = "native"

    [plugins."io.containerd.grpc.v1.cri".registry]
      [plugins."io.containerd.grpc.v1.cri".registry.configs."r.harbor.cn".auth]
        password = "password"
        username = "admin"

      [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
        [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
          endpoint = ["https://8dexs4ag.mirror.aliyuncs.com"]

        [plugins."io.containerd.grpc.v1.cri".registry.mirrors."k8s.gcr.io"]
          endpoint = ["https://r.harbor.cn"]


