

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-custom-ippool
  annotations:
    loadbalancer/ippool-name: "ippool2"
spec:
  selector:
    app: nginx-demo
  ports:
    - port: 80
  type: LoadBalancer

---

