
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wayne-mysql
  name: wayne-mysql
  namespace: default
spec:
  selector:
    app: wayne-mysql
  ports:
    - port: 3307
      protocol: TCP
      targetPort: 3306

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wayne-mysql
  namespace: default
  labels:
    app: wayne-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wayne-mysql
  template:
    metadata:
      labels:
        app: wayne-mysql
    spec:
      containers:
        - name: mysql
          image: 'mysql:5.6.41'
#          resources:
#            limits:
#              cpu: "1"
#              memory: "2Gi"
#            requests:
#              cpu: "1"
#              memory: "2Gi"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
