
# https://github.com/cilium/cilium/blob/master/install/kubernetes/experimental-install.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - configmap.yaml
  - clusterrole.yaml
  - deployment.yaml
  - daemonset.yaml
