



# 自动化生成 crd
# controller-gen -hhh
controller-gen:
	controller-gen crd:trivialVersions=true,maxDescLen=0,crdVersions=v1 paths="../../../apis/podgroup/v1" output:crd:artifacts:config=./deploy/release

