apiVersion: apps/v1
kind: Deployment
metadata:
  name: opdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: opdemo
  template:
    metadata:
      labels:
        name: opdemo
    spec:
      serviceAccountName: opdemo
      containers:
        - name: opdemo
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - opdemo
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "opdemo"
