// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64be || armbe || mips || mips64 || mips64p32 || ppc64 || s390 || s390x || sparc || sparc64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfDataCheck struct {
	IpProtocol    uint32
	SkbAddrs      [8]uint32
	SkbPorts      [2]uint16
	EthProtocol   uint16
	BindInany     uint8
	EqualCheckEnd [0]uint8
	_             [1]byte
	Len           uint32
	Hash          uint32
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

// bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	SelectBySkbData *ebpf.ProgramSpec `ebpf:"select_by_skb_data"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	DataCheckMap *ebpf.MapSpec `ebpf:"data_check_map"`
	IndexMap     *ebpf.MapSpec `ebpf:"index_map"`
	OuterMap     *ebpf.MapSpec `ebpf:"outer_map"`
	ResultMap    *ebpf.MapSpec `ebpf:"result_map"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	DataCheckMap *ebpf.Map `ebpf:"data_check_map"`
	IndexMap     *ebpf.Map `ebpf:"index_map"`
	OuterMap     *ebpf.Map `ebpf:"outer_map"`
	ResultMap    *ebpf.Map `ebpf:"result_map"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.DataCheckMap,
		m.IndexMap,
		m.OuterMap,
		m.ResultMap,
	)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	SelectBySkbData *ebpf.Program `ebpf:"select_by_skb_data"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.SelectBySkbData,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfeb.o
var _BpfBytes []byte
