/*
Copyright 2021 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	bgplbk9siov1 "k8s-lx1036/k8s/network/loadbalancer/bgplb/pkg/apis/bgplb.k9s.io/v1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBgpConves implements BgpConfInterface
type FakeBgpConves struct {
	Fake *FakeBgplbV1
	ns   string
}

var bgpconvesResource = schema.GroupVersionResource{Group: "bgplb.k9s.io", Version: "v1", Resource: "bgpconves"}

var bgpconvesKind = schema.GroupVersionKind{Group: "bgplb.k9s.io", Version: "v1", Kind: "BgpConf"}

// Get takes name of the bgpConf, and returns the corresponding bgpConf object, and an error if there is any.
func (c *FakeBgpConves) Get(ctx context.Context, name string, options v1.GetOptions) (result *bgplbk9siov1.BgpConf, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(bgpconvesResource, c.ns, name), &bgplbk9siov1.BgpConf{})

	if obj == nil {
		return nil, err
	}
	return obj.(*bgplbk9siov1.BgpConf), err
}

// List takes label and field selectors, and returns the list of BgpConves that match those selectors.
func (c *FakeBgpConves) List(ctx context.Context, opts v1.ListOptions) (result *bgplbk9siov1.BgpConfList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(bgpconvesResource, bgpconvesKind, c.ns, opts), &bgplbk9siov1.BgpConfList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &bgplbk9siov1.BgpConfList{ListMeta: obj.(*bgplbk9siov1.BgpConfList).ListMeta}
	for _, item := range obj.(*bgplbk9siov1.BgpConfList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested bgpConves.
func (c *FakeBgpConves) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(bgpconvesResource, c.ns, opts))

}

// Create takes the representation of a bgpConf and creates it.  Returns the server's representation of the bgpConf, and an error, if there is any.
func (c *FakeBgpConves) Create(ctx context.Context, bgpConf *bgplbk9siov1.BgpConf, opts v1.CreateOptions) (result *bgplbk9siov1.BgpConf, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(bgpconvesResource, c.ns, bgpConf), &bgplbk9siov1.BgpConf{})

	if obj == nil {
		return nil, err
	}
	return obj.(*bgplbk9siov1.BgpConf), err
}

// Update takes the representation of a bgpConf and updates it. Returns the server's representation of the bgpConf, and an error, if there is any.
func (c *FakeBgpConves) Update(ctx context.Context, bgpConf *bgplbk9siov1.BgpConf, opts v1.UpdateOptions) (result *bgplbk9siov1.BgpConf, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(bgpconvesResource, c.ns, bgpConf), &bgplbk9siov1.BgpConf{})

	if obj == nil {
		return nil, err
	}
	return obj.(*bgplbk9siov1.BgpConf), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBgpConves) UpdateStatus(ctx context.Context, bgpConf *bgplbk9siov1.BgpConf, opts v1.UpdateOptions) (*bgplbk9siov1.BgpConf, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(bgpconvesResource, "status", c.ns, bgpConf), &bgplbk9siov1.BgpConf{})

	if obj == nil {
		return nil, err
	}
	return obj.(*bgplbk9siov1.BgpConf), err
}

// Delete takes name of the bgpConf and deletes it. Returns an error if one occurs.
func (c *FakeBgpConves) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(bgpconvesResource, c.ns, name), &bgplbk9siov1.BgpConf{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBgpConves) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(bgpconvesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &bgplbk9siov1.BgpConfList{})
	return err
}

// Patch applies the patch and returns the patched bgpConf.
func (c *FakeBgpConves) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *bgplbk9siov1.BgpConf, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(bgpconvesResource, c.ns, name, pt, data, subresources...), &bgplbk9siov1.BgpConf{})

	if obj == nil {
		return nil, err
	}
	return obj.(*bgplbk9siov1.BgpConf), err
}
