/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	bgplbk9siov1 "k8s-lx1036/k8s/network/loadbalancer/bgplb/pkg/apis/bgplb.k9s.io/v1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBgpPeers implements BgpPeerInterface
type FakeBgpPeers struct {
	Fake *FakeBgplbV1
}

var bgppeersResource = schema.GroupVersionResource{Group: "bgplb.k9s.io", Version: "v1", Resource: "bgppeers"}

var bgppeersKind = schema.GroupVersionKind{Group: "bgplb.k9s.io", Version: "v1", Kind: "BgpPeer"}

// Get takes name of the bgpPeer, and returns the corresponding bgpPeer object, and an error if there is any.
func (c *FakeBgpPeers) Get(ctx context.Context, name string, options v1.GetOptions) (result *bgplbk9siov1.BgpPeer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(bgppeersResource, name), &bgplbk9siov1.BgpPeer{})
	if obj == nil {
		return nil, err
	}
	return obj.(*bgplbk9siov1.BgpPeer), err
}

// List takes label and field selectors, and returns the list of BgpPeers that match those selectors.
func (c *FakeBgpPeers) List(ctx context.Context, opts v1.ListOptions) (result *bgplbk9siov1.BgpPeerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(bgppeersResource, bgppeersKind, opts), &bgplbk9siov1.BgpPeerList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &bgplbk9siov1.BgpPeerList{ListMeta: obj.(*bgplbk9siov1.BgpPeerList).ListMeta}
	for _, item := range obj.(*bgplbk9siov1.BgpPeerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested bgpPeers.
func (c *FakeBgpPeers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(bgppeersResource, opts))
}

// Create takes the representation of a bgpPeer and creates it.  Returns the server's representation of the bgpPeer, and an error, if there is any.
func (c *FakeBgpPeers) Create(ctx context.Context, bgpPeer *bgplbk9siov1.BgpPeer, opts v1.CreateOptions) (result *bgplbk9siov1.BgpPeer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(bgppeersResource, bgpPeer), &bgplbk9siov1.BgpPeer{})
	if obj == nil {
		return nil, err
	}
	return obj.(*bgplbk9siov1.BgpPeer), err
}

// Update takes the representation of a bgpPeer and updates it. Returns the server's representation of the bgpPeer, and an error, if there is any.
func (c *FakeBgpPeers) Update(ctx context.Context, bgpPeer *bgplbk9siov1.BgpPeer, opts v1.UpdateOptions) (result *bgplbk9siov1.BgpPeer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(bgppeersResource, bgpPeer), &bgplbk9siov1.BgpPeer{})
	if obj == nil {
		return nil, err
	}
	return obj.(*bgplbk9siov1.BgpPeer), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBgpPeers) UpdateStatus(ctx context.Context, bgpPeer *bgplbk9siov1.BgpPeer, opts v1.UpdateOptions) (*bgplbk9siov1.BgpPeer, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(bgppeersResource, "status", bgpPeer), &bgplbk9siov1.BgpPeer{})
	if obj == nil {
		return nil, err
	}
	return obj.(*bgplbk9siov1.BgpPeer), err
}

// Delete takes name of the bgpPeer and deletes it. Returns an error if one occurs.
func (c *FakeBgpPeers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(bgppeersResource, name), &bgplbk9siov1.BgpPeer{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBgpPeers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(bgppeersResource, listOpts)

	_, err := c.Fake.Invokes(action, &bgplbk9siov1.BgpPeerList{})
	return err
}

// Patch applies the patch and returns the patched bgpPeer.
func (c *FakeBgpPeers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *bgplbk9siov1.BgpPeer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(bgppeersResource, name, pt, data, subresources...), &bgplbk9siov1.BgpPeer{})
	if obj == nil {
		return nil, err
	}
	return obj.(*bgplbk9siov1.BgpPeer), err
}
