
# local storage class
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage-task
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: local-storage-task
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany # 读写权限，可以被多个节点挂载; ReadWriteOnce 只能挂载在一个节点上
  hostPath:
    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: task2-pv-volume
  labels:
    type: local
spec:
  storageClassName: local-storage-task2
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany # 读写权限，可以被多个节点挂载; ReadWriteOnce 只能挂载在一个节点上
  hostPath:
    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hostpath
spec:
  storageClassName: local-storage-task
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
