// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: rpc.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action int32

const (
	Action_ADD Action = 0
	Action_DEL Action = 1
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "ADD",
		1: "DEL",
	}
	Action_value = map[string]int32{
		"ADD": 0,
		"DEL": 1,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_rpc_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{0}
}

type Bool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *Bool) Reset() {
	*x = Bool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bool) ProtoMessage() {}

func (x *Bool) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bool.ProtoReflect.Descriptor instead.
func (*Bool) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *Bool) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Vip struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address  string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Port     int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Protocol string `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
}

func (x *Vip) Reset() {
	*x = Vip{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vip) ProtoMessage() {}

func (x *Vip) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vip.ProtoReflect.Descriptor instead.
func (*Vip) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *Vip) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Vip) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Vip) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type VipMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vip   *Vip  `protobuf:"bytes,1,opt,name=vip,proto3" json:"vip,omitempty"`
	Flags int64 `protobuf:"varint,2,opt,name=flags,proto3" json:"flags,omitempty"`
	// setFlag controls if we setting this flags or removing it from the VIP
	SetFlag bool `protobuf:"varint,3,opt,name=setFlag,proto3" json:"setFlag,omitempty"`
}

func (x *VipMeta) Reset() {
	*x = VipMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VipMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VipMeta) ProtoMessage() {}

func (x *VipMeta) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VipMeta.ProtoReflect.Descriptor instead.
func (*VipMeta) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *VipMeta) GetVip() *Vip {
	if x != nil {
		return x.Vip
	}
	return nil
}

func (x *VipMeta) GetFlags() int64 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *VipMeta) GetSetFlag() bool {
	if x != nil {
		return x.SetFlag
	}
	return false
}

type RealMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Flags   int32  `protobuf:"varint,2,opt,name=flags,proto3" json:"flags,omitempty"`
	// setFlag controls if we setting this flags or removing it from the Real
	SetFlag bool `protobuf:"varint,3,opt,name=setFlag,proto3" json:"setFlag,omitempty"`
}

func (x *RealMeta) Reset() {
	*x = RealMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RealMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealMeta) ProtoMessage() {}

func (x *RealMeta) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealMeta.ProtoReflect.Descriptor instead.
func (*RealMeta) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *RealMeta) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RealMeta) GetFlags() int32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *RealMeta) GetSetFlag() bool {
	if x != nil {
		return x.SetFlag
	}
	return false
}

type Real struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Weight  int32  `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	Flags   int32  `protobuf:"varint,3,opt,name=flags,proto3" json:"flags,omitempty"`
}

func (x *Real) Reset() {
	*x = Real{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Real) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Real) ProtoMessage() {}

func (x *Real) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Real.ProtoReflect.Descriptor instead.
func (*Real) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *Real) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Real) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Real) GetFlags() int32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

type QuicReal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Id      int32  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *QuicReal) Reset() {
	*x = QuicReal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuicReal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuicReal) ProtoMessage() {}

func (x *QuicReal) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuicReal.ProtoReflect.Descriptor instead.
func (*QuicReal) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *QuicReal) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *QuicReal) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Mac struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mac string `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
}

func (x *Mac) Reset() {
	*x = Mac{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mac) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mac) ProtoMessage() {}

func (x *Mac) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mac.ProtoReflect.Descriptor instead.
func (*Mac) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *Mac) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

type Stats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	V1 uint64 `protobuf:"varint,1,opt,name=v1,proto3" json:"v1,omitempty"`
	V2 uint64 `protobuf:"varint,2,opt,name=v2,proto3" json:"v2,omitempty"`
}

func (x *Stats) Reset() {
	*x = Stats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *Stats) GetV1() uint64 {
	if x != nil {
		return x.V1
	}
	return 0
}

func (x *Stats) GetV2() uint64 {
	if x != nil {
		return x.V2
	}
	return 0
}

type Healthcheck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Somark  uint32 `protobuf:"varint,1,opt,name=somark,proto3" json:"somark,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *Healthcheck) Reset() {
	*x = Healthcheck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Healthcheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Healthcheck) ProtoMessage() {}

func (x *Healthcheck) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Healthcheck.ProtoReflect.Descriptor instead.
func (*Healthcheck) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *Healthcheck) GetSomark() uint32 {
	if x != nil {
		return x.Somark
	}
	return 0
}

func (x *Healthcheck) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type HcMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Healthchecks map[int32]string `protobuf:"bytes,1,rep,name=healthchecks,proto3" json:"healthchecks,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *HcMap) Reset() {
	*x = HcMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HcMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HcMap) ProtoMessage() {}

func (x *HcMap) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HcMap.ProtoReflect.Descriptor instead.
func (*HcMap) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *HcMap) GetHealthchecks() map[int32]string {
	if x != nil {
		return x.Healthchecks
	}
	return nil
}

type Reals struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reals []*Real `protobuf:"bytes,1,rep,name=reals,proto3" json:"reals,omitempty"`
}

func (x *Reals) Reset() {
	*x = Reals{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reals) ProtoMessage() {}

func (x *Reals) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reals.ProtoReflect.Descriptor instead.
func (*Reals) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{11}
}

func (x *Reals) GetReals() []*Real {
	if x != nil {
		return x.Reals
	}
	return nil
}

type Vips struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vips []*Vip `protobuf:"bytes,1,rep,name=vips,proto3" json:"vips,omitempty"`
}

func (x *Vips) Reset() {
	*x = Vips{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vips) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vips) ProtoMessage() {}

func (x *Vips) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vips.ProtoReflect.Descriptor instead.
func (*Vips) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{12}
}

func (x *Vips) GetVips() []*Vip {
	if x != nil {
		return x.Vips
	}
	return nil
}

type QuicReals struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Qreals []*QuicReal `protobuf:"bytes,1,rep,name=qreals,proto3" json:"qreals,omitempty"`
}

func (x *QuicReals) Reset() {
	*x = QuicReals{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuicReals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuicReals) ProtoMessage() {}

func (x *QuicReals) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuicReals.ProtoReflect.Descriptor instead.
func (*QuicReals) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{13}
}

func (x *QuicReals) GetQreals() []*QuicReal {
	if x != nil {
		return x.Qreals
	}
	return nil
}

type ModifiedRealsForVip struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action Action `protobuf:"varint,1,opt,name=action,proto3,enum=rpc.Action" json:"action,omitempty"`
	Real   *Reals `protobuf:"bytes,2,opt,name=real,proto3" json:"real,omitempty"`
	Vip    *Vip   `protobuf:"bytes,3,opt,name=vip,proto3" json:"vip,omitempty"`
}

func (x *ModifiedRealsForVip) Reset() {
	*x = ModifiedRealsForVip{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifiedRealsForVip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifiedRealsForVip) ProtoMessage() {}

func (x *ModifiedRealsForVip) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifiedRealsForVip.ProtoReflect.Descriptor instead.
func (*ModifiedRealsForVip) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{14}
}

func (x *ModifiedRealsForVip) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ADD
}

func (x *ModifiedRealsForVip) GetReal() *Reals {
	if x != nil {
		return x.Real
	}
	return nil
}

func (x *ModifiedRealsForVip) GetVip() *Vip {
	if x != nil {
		return x.Vip
	}
	return nil
}

type ModifiedQuicReals struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action Action     `protobuf:"varint,1,opt,name=action,proto3,enum=rpc.Action" json:"action,omitempty"`
	Reals  *QuicReals `protobuf:"bytes,2,opt,name=reals,proto3" json:"reals,omitempty"`
}

func (x *ModifiedQuicReals) Reset() {
	*x = ModifiedQuicReals{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifiedQuicReals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifiedQuicReals) ProtoMessage() {}

func (x *ModifiedQuicReals) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifiedQuicReals.ProtoReflect.Descriptor instead.
func (*ModifiedQuicReals) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{15}
}

func (x *ModifiedQuicReals) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ADD
}

func (x *ModifiedQuicReals) GetReals() *QuicReals {
	if x != nil {
		return x.Reals
	}
	return nil
}

type RealForVip struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Real *Real `protobuf:"bytes,1,opt,name=real,proto3" json:"real,omitempty"`
	Vip  *Vip  `protobuf:"bytes,2,opt,name=vip,proto3" json:"vip,omitempty"`
}

func (x *RealForVip) Reset() {
	*x = RealForVip{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RealForVip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealForVip) ProtoMessage() {}

func (x *RealForVip) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealForVip.ProtoReflect.Descriptor instead.
func (*RealForVip) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{16}
}

func (x *RealForVip) GetReal() *Real {
	if x != nil {
		return x.Real
	}
	return nil
}

func (x *RealForVip) GetVip() *Vip {
	if x != nil {
		return x.Vip
	}
	return nil
}

type Flags struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flags uint64 `protobuf:"varint,1,opt,name=flags,proto3" json:"flags,omitempty"`
}

func (x *Flags) Reset() {
	*x = Flags{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Flags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flags) ProtoMessage() {}

func (x *Flags) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flags.ProtoReflect.Descriptor instead.
func (*Flags) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{17}
}

func (x *Flags) GetFlags() uint64 {
	if x != nil {
		return x.Flags
	}
	return 0
}

type Somark struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Somark uint32 `protobuf:"varint,1,opt,name=somark,proto3" json:"somark,omitempty"`
}

func (x *Somark) Reset() {
	*x = Somark{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Somark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Somark) ProtoMessage() {}

func (x *Somark) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Somark.ProtoReflect.Descriptor instead.
func (*Somark) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{18}
}

func (x *Somark) GetSomark() uint32 {
	if x != nil {
		return x.Somark
	}
	return 0
}

var File_rpc_proto protoreflect.FileDescriptor

var file_rpc_proto_rawDesc = []byte{
	0x0a, 0x09, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x70, 0x63,
	0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x20, 0x0a, 0x04, 0x42, 0x6f, 0x6f,
	0x6c, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x4f, 0x0a, 0x03, 0x56,
	0x69, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0x55, 0x0a, 0x07,
	0x56, 0x69, 0x70, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x03, 0x76, 0x69, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x69, 0x70, 0x52, 0x03,
	0x76, 0x69, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x74,
	0x46, 0x6c, 0x61, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x65, 0x74, 0x46,
	0x6c, 0x61, 0x67, 0x22, 0x54, 0x0a, 0x08, 0x52, 0x65, 0x61, 0x6c, 0x4d, 0x65, 0x74, 0x61, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6c, 0x61,
	0x67, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x65, 0x74, 0x46, 0x6c, 0x61, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x65, 0x74, 0x46, 0x6c, 0x61, 0x67, 0x22, 0x4e, 0x0a, 0x04, 0x52, 0x65, 0x61,
	0x6c, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x77,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x77, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x22, 0x34, 0x0a, 0x08, 0x51, 0x75, 0x69,
	0x63, 0x52, 0x65, 0x61, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x17, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x63, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x61, 0x63, 0x22, 0x27, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x76,
	0x31, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x76,
	0x32, 0x22, 0x3f, 0x0a, 0x0b, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x73, 0x6f, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x22, 0x8a, 0x01, 0x0a, 0x05, 0x68, 0x63, 0x4d, 0x61, 0x70, 0x12, 0x40, 0x0a, 0x0c,
	0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x68, 0x63, 0x4d, 0x61, 0x70, 0x2e, 0x48,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x0c, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x1a, 0x3f,
	0x0a, 0x11, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0x28, 0x0a, 0x05, 0x52, 0x65, 0x61, 0x6c, 0x73, 0x12, 0x1f, 0x0a, 0x05, 0x72, 0x65, 0x61, 0x6c,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65,
	0x61, 0x6c, 0x52, 0x05, 0x72, 0x65, 0x61, 0x6c, 0x73, 0x22, 0x24, 0x0a, 0x04, 0x56, 0x69, 0x70,
	0x73, 0x12, 0x1c, 0x0a, 0x04, 0x76, 0x69, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x08, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x69, 0x70, 0x52, 0x04, 0x76, 0x69, 0x70, 0x73, 0x22,
	0x32, 0x0a, 0x09, 0x51, 0x75, 0x69, 0x63, 0x52, 0x65, 0x61, 0x6c, 0x73, 0x12, 0x25, 0x0a, 0x06,
	0x71, 0x72, 0x65, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x51, 0x75, 0x69, 0x63, 0x52, 0x65, 0x61, 0x6c, 0x52, 0x06, 0x71, 0x72, 0x65,
	0x61, 0x6c, 0x73, 0x22, 0x76, 0x0a, 0x13, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x52,
	0x65, 0x61, 0x6c, 0x73, 0x46, 0x6f, 0x72, 0x56, 0x69, 0x70, 0x12, 0x23, 0x0a, 0x06, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1e, 0x0a, 0x04, 0x72, 0x65, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x61, 0x6c, 0x73, 0x52, 0x04, 0x72, 0x65, 0x61, 0x6c, 0x12,
	0x1a, 0x0a, 0x03, 0x76, 0x69, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x56, 0x69, 0x70, 0x52, 0x03, 0x76, 0x69, 0x70, 0x22, 0x5e, 0x0a, 0x11, 0x6d,
	0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x51, 0x75, 0x69, 0x63, 0x52, 0x65, 0x61, 0x6c, 0x73,
	0x12, 0x23, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x05, 0x72, 0x65, 0x61, 0x6c, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x51, 0x75, 0x69, 0x63, 0x52,
	0x65, 0x61, 0x6c, 0x73, 0x52, 0x05, 0x72, 0x65, 0x61, 0x6c, 0x73, 0x22, 0x47, 0x0a, 0x0a, 0x72,
	0x65, 0x61, 0x6c, 0x46, 0x6f, 0x72, 0x56, 0x69, 0x70, 0x12, 0x1d, 0x0a, 0x04, 0x72, 0x65, 0x61,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65,
	0x61, 0x6c, 0x52, 0x04, 0x72, 0x65, 0x61, 0x6c, 0x12, 0x1a, 0x0a, 0x03, 0x76, 0x69, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x69, 0x70, 0x52,
	0x03, 0x76, 0x69, 0x70, 0x22, 0x1d, 0x0a, 0x05, 0x46, 0x6c, 0x61, 0x67, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x66, 0x6c,
	0x61, 0x67, 0x73, 0x22, 0x20, 0x0a, 0x06, 0x53, 0x6f, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x6f, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73,
	0x6f, 0x6d, 0x61, 0x72, 0x6b, 0x2a, 0x1a, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x07, 0x0a, 0x03, 0x41, 0x44, 0x44, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x45, 0x4c, 0x10,
	0x01, 0x32, 0xe8, 0x07, 0x0a, 0x0d, 0x4f, 0x70, 0x65, 0x6e, 0x4c, 0x62, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x61, 0x63,
	0x12, 0x08, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x61, 0x63, 0x1a, 0x09, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x1e, 0x0a, 0x06, 0x67, 0x65, 0x74, 0x4d, 0x61, 0x63, 0x12,
	0x0a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x08, 0x2e, 0x72, 0x70,
	0x63, 0x2e, 0x4d, 0x61, 0x63, 0x12, 0x21, 0x0a, 0x06, 0x61, 0x64, 0x64, 0x56, 0x69, 0x70, 0x12,
	0x0c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x69, 0x70, 0x4d, 0x65, 0x74, 0x61, 0x1a, 0x09, 0x2e,
	0x72, 0x70, 0x63, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x1d, 0x0a, 0x06, 0x64, 0x65, 0x6c, 0x56,
	0x69, 0x70, 0x12, 0x08, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x69, 0x70, 0x1a, 0x09, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x23, 0x0a, 0x0a, 0x67, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x56, 0x69, 0x70, 0x73, 0x12, 0x0a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x09, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x69, 0x70, 0x73, 0x12, 0x24, 0x0a, 0x09,
	0x6d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x56, 0x69, 0x70, 0x12, 0x0c, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x56, 0x69, 0x70, 0x4d, 0x65, 0x74, 0x61, 0x1a, 0x09, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x42, 0x6f,
	0x6f, 0x6c, 0x12, 0x26, 0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x52, 0x65, 0x61, 0x6c,
	0x12, 0x0d, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x61, 0x6c, 0x4d, 0x65, 0x74, 0x61, 0x1a,
	0x09, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x23, 0x0a, 0x0b, 0x67, 0x65,
	0x74, 0x56, 0x69, 0x70, 0x46, 0x6c, 0x61, 0x67, 0x73, 0x12, 0x08, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x56, 0x69, 0x70, 0x1a, 0x0a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x46, 0x6c, 0x61, 0x67, 0x73, 0x12,
	0x25, 0x0a, 0x0c, 0x67, 0x65, 0x74, 0x52, 0x65, 0x61, 0x6c, 0x46, 0x6c, 0x61, 0x67, 0x73, 0x12,
	0x09, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x61, 0x6c, 0x1a, 0x0a, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x46, 0x6c, 0x61, 0x67, 0x73, 0x12, 0x2b, 0x0a, 0x0d, 0x61, 0x64, 0x64, 0x52, 0x65, 0x61,
	0x6c, 0x46, 0x6f, 0x72, 0x56, 0x69, 0x70, 0x12, 0x0f, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x72, 0x65,
	0x61, 0x6c, 0x46, 0x6f, 0x72, 0x56, 0x69, 0x70, 0x1a, 0x09, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x42,
	0x6f, 0x6f, 0x6c, 0x12, 0x2b, 0x0a, 0x0d, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x61, 0x6c, 0x46, 0x6f,
	0x72, 0x56, 0x69, 0x70, 0x12, 0x0f, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x72, 0x65, 0x61, 0x6c, 0x46,
	0x6f, 0x72, 0x56, 0x69, 0x70, 0x1a, 0x09, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x42, 0x6f, 0x6f, 0x6c,
	0x12, 0x38, 0x0a, 0x11, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x52, 0x65, 0x61, 0x6c, 0x73, 0x46,
	0x6f, 0x72, 0x56, 0x69, 0x70, 0x12, 0x18, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x6d, 0x6f, 0x64, 0x69,
	0x66, 0x69, 0x65, 0x64, 0x52, 0x65, 0x61, 0x6c, 0x73, 0x46, 0x6f, 0x72, 0x56, 0x69, 0x70, 0x1a,
	0x09, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x26, 0x0a, 0x0e, 0x67, 0x65,
	0x74, 0x52, 0x65, 0x61, 0x6c, 0x73, 0x46, 0x6f, 0x72, 0x56, 0x69, 0x70, 0x12, 0x08, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x56, 0x69, 0x70, 0x1a, 0x0a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x61,
	0x6c, 0x73, 0x12, 0x3b, 0x0a, 0x16, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x51, 0x75, 0x69, 0x63,
	0x52, 0x65, 0x61, 0x6c, 0x73, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x51, 0x75, 0x69, 0x63, 0x52,
	0x65, 0x61, 0x6c, 0x73, 0x1a, 0x09, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x12,
	0x31, 0x0a, 0x13, 0x67, 0x65, 0x74, 0x51, 0x75, 0x69, 0x63, 0x52, 0x65, 0x61, 0x6c, 0x73, 0x4d,
	0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x0a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x0e, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x51, 0x75, 0x69, 0x63, 0x52, 0x65, 0x61,
	0x6c, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x67, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x46, 0x6f,
	0x72, 0x56, 0x69, 0x70, 0x12, 0x08, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x69, 0x70, 0x1a, 0x0a,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x25, 0x0a, 0x0b, 0x67, 0x65,
	0x74, 0x4c, 0x72, 0x75, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x0a, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x12, 0x29, 0x0a, 0x0f, 0x67, 0x65, 0x74, 0x4c, 0x72, 0x75, 0x4d, 0x69, 0x73, 0x73, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x12, 0x0a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x0a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x2d, 0x0a, 0x13,
	0x67, 0x65, 0x74, 0x4c, 0x72, 0x75, 0x46, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x53, 0x74,
	0x61, 0x74, 0x73, 0x12, 0x0a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x0a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x2c, 0x0a, 0x12, 0x67,
	0x65, 0x74, 0x49, 0x63, 0x6d, 0x70, 0x54, 0x6f, 0x6f, 0x42, 0x69, 0x67, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x12, 0x0a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0a, 0x2e,
	0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x32, 0x0a, 0x13, 0x61, 0x64, 0x64,
	0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x44, 0x73, 0x74,
	0x12, 0x10, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x1a, 0x09, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x2d, 0x0a,
	0x13, 0x64, 0x65, 0x6c, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65,
	0x72, 0x44, 0x73, 0x74, 0x12, 0x0b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x6f, 0x6d, 0x61, 0x72,
	0x6b, 0x1a, 0x09, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x2e, 0x0a, 0x14,
	0x67, 0x65, 0x74, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72,
	0x73, 0x44, 0x73, 0x74, 0x12, 0x0a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x0a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x68, 0x63, 0x4d, 0x61, 0x70, 0x42, 0x08, 0x5a, 0x06,
	0x2e, 0x2f, 0x3b, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_proto_rawDescOnce sync.Once
	file_rpc_proto_rawDescData = file_rpc_proto_rawDesc
)

func file_rpc_proto_rawDescGZIP() []byte {
	file_rpc_proto_rawDescOnce.Do(func() {
		file_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_proto_rawDescData)
	})
	return file_rpc_proto_rawDescData
}

var file_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_rpc_proto_goTypes = []interface{}{
	(Action)(0),                 // 0: rpc.Action
	(*Empty)(nil),               // 1: rpc.Empty
	(*Bool)(nil),                // 2: rpc.Bool
	(*Vip)(nil),                 // 3: rpc.Vip
	(*VipMeta)(nil),             // 4: rpc.VipMeta
	(*RealMeta)(nil),            // 5: rpc.RealMeta
	(*Real)(nil),                // 6: rpc.Real
	(*QuicReal)(nil),            // 7: rpc.QuicReal
	(*Mac)(nil),                 // 8: rpc.Mac
	(*Stats)(nil),               // 9: rpc.Stats
	(*Healthcheck)(nil),         // 10: rpc.Healthcheck
	(*HcMap)(nil),               // 11: rpc.hcMap
	(*Reals)(nil),               // 12: rpc.Reals
	(*Vips)(nil),                // 13: rpc.Vips
	(*QuicReals)(nil),           // 14: rpc.QuicReals
	(*ModifiedRealsForVip)(nil), // 15: rpc.modifiedRealsForVip
	(*ModifiedQuicReals)(nil),   // 16: rpc.modifiedQuicReals
	(*RealForVip)(nil),          // 17: rpc.realForVip
	(*Flags)(nil),               // 18: rpc.Flags
	(*Somark)(nil),              // 19: rpc.Somark
	nil,                         // 20: rpc.hcMap.HealthchecksEntry
}
var file_rpc_proto_depIdxs = []int32{
	3,  // 0: rpc.VipMeta.vip:type_name -> rpc.Vip
	20, // 1: rpc.hcMap.healthchecks:type_name -> rpc.hcMap.HealthchecksEntry
	6,  // 2: rpc.Reals.reals:type_name -> rpc.Real
	3,  // 3: rpc.Vips.vips:type_name -> rpc.Vip
	7,  // 4: rpc.QuicReals.qreals:type_name -> rpc.QuicReal
	0,  // 5: rpc.modifiedRealsForVip.action:type_name -> rpc.Action
	12, // 6: rpc.modifiedRealsForVip.real:type_name -> rpc.Reals
	3,  // 7: rpc.modifiedRealsForVip.vip:type_name -> rpc.Vip
	0,  // 8: rpc.modifiedQuicReals.action:type_name -> rpc.Action
	14, // 9: rpc.modifiedQuicReals.reals:type_name -> rpc.QuicReals
	6,  // 10: rpc.realForVip.real:type_name -> rpc.Real
	3,  // 11: rpc.realForVip.vip:type_name -> rpc.Vip
	8,  // 12: rpc.OpenLbService.changeMac:input_type -> rpc.Mac
	1,  // 13: rpc.OpenLbService.getMac:input_type -> rpc.Empty
	4,  // 14: rpc.OpenLbService.addVip:input_type -> rpc.VipMeta
	3,  // 15: rpc.OpenLbService.delVip:input_type -> rpc.Vip
	1,  // 16: rpc.OpenLbService.getAllVips:input_type -> rpc.Empty
	4,  // 17: rpc.OpenLbService.modifyVip:input_type -> rpc.VipMeta
	5,  // 18: rpc.OpenLbService.modifyReal:input_type -> rpc.RealMeta
	3,  // 19: rpc.OpenLbService.getVipFlags:input_type -> rpc.Vip
	6,  // 20: rpc.OpenLbService.getRealFlags:input_type -> rpc.Real
	17, // 21: rpc.OpenLbService.addRealForVip:input_type -> rpc.realForVip
	17, // 22: rpc.OpenLbService.delRealForVip:input_type -> rpc.realForVip
	15, // 23: rpc.OpenLbService.modifyRealsForVip:input_type -> rpc.modifiedRealsForVip
	3,  // 24: rpc.OpenLbService.getRealsForVip:input_type -> rpc.Vip
	16, // 25: rpc.OpenLbService.modifyQuicRealsMapping:input_type -> rpc.modifiedQuicReals
	1,  // 26: rpc.OpenLbService.getQuicRealsMapping:input_type -> rpc.Empty
	3,  // 27: rpc.OpenLbService.getStatsForVip:input_type -> rpc.Vip
	1,  // 28: rpc.OpenLbService.getLruStats:input_type -> rpc.Empty
	1,  // 29: rpc.OpenLbService.getLruMissStats:input_type -> rpc.Empty
	1,  // 30: rpc.OpenLbService.getLruFallbackStats:input_type -> rpc.Empty
	1,  // 31: rpc.OpenLbService.getIcmpTooBigStats:input_type -> rpc.Empty
	10, // 32: rpc.OpenLbService.addHealthcheckerDst:input_type -> rpc.Healthcheck
	19, // 33: rpc.OpenLbService.delHealthcheckerDst:input_type -> rpc.Somark
	1,  // 34: rpc.OpenLbService.getHealthcheckersDst:input_type -> rpc.Empty
	2,  // 35: rpc.OpenLbService.changeMac:output_type -> rpc.Bool
	8,  // 36: rpc.OpenLbService.getMac:output_type -> rpc.Mac
	2,  // 37: rpc.OpenLbService.addVip:output_type -> rpc.Bool
	2,  // 38: rpc.OpenLbService.delVip:output_type -> rpc.Bool
	13, // 39: rpc.OpenLbService.getAllVips:output_type -> rpc.Vips
	2,  // 40: rpc.OpenLbService.modifyVip:output_type -> rpc.Bool
	2,  // 41: rpc.OpenLbService.modifyReal:output_type -> rpc.Bool
	18, // 42: rpc.OpenLbService.getVipFlags:output_type -> rpc.Flags
	18, // 43: rpc.OpenLbService.getRealFlags:output_type -> rpc.Flags
	2,  // 44: rpc.OpenLbService.addRealForVip:output_type -> rpc.Bool
	2,  // 45: rpc.OpenLbService.delRealForVip:output_type -> rpc.Bool
	2,  // 46: rpc.OpenLbService.modifyRealsForVip:output_type -> rpc.Bool
	12, // 47: rpc.OpenLbService.getRealsForVip:output_type -> rpc.Reals
	2,  // 48: rpc.OpenLbService.modifyQuicRealsMapping:output_type -> rpc.Bool
	14, // 49: rpc.OpenLbService.getQuicRealsMapping:output_type -> rpc.QuicReals
	9,  // 50: rpc.OpenLbService.getStatsForVip:output_type -> rpc.Stats
	9,  // 51: rpc.OpenLbService.getLruStats:output_type -> rpc.Stats
	9,  // 52: rpc.OpenLbService.getLruMissStats:output_type -> rpc.Stats
	9,  // 53: rpc.OpenLbService.getLruFallbackStats:output_type -> rpc.Stats
	9,  // 54: rpc.OpenLbService.getIcmpTooBigStats:output_type -> rpc.Stats
	2,  // 55: rpc.OpenLbService.addHealthcheckerDst:output_type -> rpc.Bool
	2,  // 56: rpc.OpenLbService.delHealthcheckerDst:output_type -> rpc.Bool
	11, // 57: rpc.OpenLbService.getHealthcheckersDst:output_type -> rpc.hcMap
	35, // [35:58] is the sub-list for method output_type
	12, // [12:35] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_rpc_proto_init() }
func file_rpc_proto_init() {
	if File_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vip); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VipMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RealMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Real); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuicReal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mac); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Healthcheck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HcMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reals); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vips); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuicReals); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifiedRealsForVip); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifiedQuicReals); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RealForVip); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Flags); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Somark); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_proto_goTypes,
		DependencyIndexes: file_rpc_proto_depIdxs,
		EnumInfos:         file_rpc_proto_enumTypes,
		MessageInfos:      file_rpc_proto_msgTypes,
	}.Build()
	File_rpc_proto = out.File
	file_rpc_proto_rawDesc = nil
	file_rpc_proto_goTypes = nil
	file_rpc_proto_depIdxs = nil
}
