version: 0.1
log:
  level: info
  fields:
    service: registry
storage:
  cache:
    layerinfo: redis
  filesystem:
    rootdirectory: /var/lib/registry
    maxthreads: 100
  maintenance:
    uploadpurging:
      enabled: false
  delete:
    enabled: true
redis:
  addr: redis.svc.default:6379
  db: 0
  dialtimeout: 10ms
  readtimeout: 10ms
  writetimeout: 10ms
  pool:
    maxidle: 16
    maxactive: 64
    idletimeout: 300s
http:
  addr: :5000
  secret: placeholder
  debug:
    addr: localhost:5001
#auth:
#  token:
#    issuer: harbor-token-issuer
#    realm: $public_url/service/token
#    rootcertbundle: /etc/registry/root.crt
#    service: harbor-registry
#notifications:
#  endpoints:
#    - name: harbor
#      disabled: false
#      url: $ui_url/service/notifications
#      timeout: 3000ms
#      threshold: 5
#      backoff: 1s
