
- name: prepare some dirs
  file: name={{ item }} state=directory
  with_items:
#    - "{{ bin_dir }}"
#    - "{{ ca_dir }}"
    - /tmp/.kube

- name: "copy files"
  copy:
    src: '{{item}}'
    dest: '/tmp/{{item}}'
  with_items:
    - server_a

- name: "template conf file"
  template:
    src: config_a.ini.j2
    dest: /tmp/config_a.ini
  with_items:
    - config_a.ini
