
# 针对 cilium v1.8.1 版本 vxlan，新版本需要更新参数
# cilium vxlan 是如何工作的？？？有 cilium_vxlan 网卡。

#  cilium bpf tunnel list
#  TUNNEL           VALUE
#  20.225.2.0:0     172.16.7.57:0
#  20.225.0.128:0   172.16.1.224:0
#  20.225.4.128:0   172.16.1.114:0
#  20.225.1.128:0   172.16.8.48:0
#  20.225.0.0:0     172.16.4.153:0
#  20.225.1.0:0     172.16.1.207:0
#  20.225.3.0:0     172.16.7.230:0
#  20.225.4.0:0     172.16.6.105:0
#  20.225.2.128:0   172.16.9.80:0

apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-config
  namespace: kube-system
data:
  auto-direct-node-routes: 'false'
  bpf-map-dynamic-size-ratio: '0.0025'
  bpf-policy-map-max: '16384'
  cluster-name: default
  cluster-pool-ipv4-cidr: 20.225.0.0/16
  cluster-pool-ipv4-mask-size: '25'
  debug: 'false'
  disable-cnp-status-updates: 'true'
  enable-auto-protect-node-port-range: 'true'
  enable-bpf-clock-probe: 'true'
  enable-bpf-masquerade: 'true'
  enable-endpoint-health-checking: 'true'
  enable-ipv4: 'true'
  enable-ipv6: 'false'
  enable-remote-node-identity: 'true'
  enable-session-affinity: 'true'
  enable-well-known-identities: 'false'
  enable-xt-socket-fallback: 'true'
  identity-allocation-mode: crd
  install-iptables-rules: 'true'
  ipam: cluster-pool
  k8s-require-ipv4-pod-cidr: 'true'
  k8s-require-ipv6-pod-cidr: 'false'
  kube-proxy-replacement: probe
  masquerade: 'true'
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  native-routing-cidr: 20.225.0.0/16
  node-port-bind-protection: 'true'
  node-port-mode: dsr
  operator-api-serve-addr: 127.0.0.1:9234
  preallocate-bpf-maps: 'false'
  sidecar-istio-proxy-image: cilium/istio_proxy
  tofqdns-enable-poller: 'false'
  tunnel: vxlan
  wait-bpf-mount: 'false'
