
apiVersion: v1
kind: Pod
metadata:
  name: serviceaccount-admission-plugin
  labels:
    app: serviceaccount-admission-plugin
spec:
  containers:
    - name: serviceaccount-admission-plugin
      image: nginx:1.24.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          name: "http-server"
