// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || amd64p32 || arm || arm64 || loong64 || mips64le || mips64p32le || mipsle || ppc64le || riscv64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfSockoptInherit struct{ Val uint8 }

type bpfSockoptSk struct{ Val uint8 }

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

// bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	Getsockopt1 *ebpf.ProgramSpec `ebpf:"getsockopt1"`
	Getsockopt2 *ebpf.ProgramSpec `ebpf:"getsockopt2"`
	Setsockopt1 *ebpf.ProgramSpec `ebpf:"setsockopt1"`
	Setsockopt2 *ebpf.ProgramSpec `ebpf:"setsockopt2"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	Cloned1Map       *ebpf.MapSpec `ebpf:"cloned1_map"`
	Cloned2Map       *ebpf.MapSpec `ebpf:"cloned2_map"`
	ListenerOnlyMap  *ebpf.MapSpec `ebpf:"listener_only_map"`
	SocketStorageMap *ebpf.MapSpec `ebpf:"socket_storage_map"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	Cloned1Map       *ebpf.Map `ebpf:"cloned1_map"`
	Cloned2Map       *ebpf.Map `ebpf:"cloned2_map"`
	ListenerOnlyMap  *ebpf.Map `ebpf:"listener_only_map"`
	SocketStorageMap *ebpf.Map `ebpf:"socket_storage_map"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.Cloned1Map,
		m.Cloned2Map,
		m.ListenerOnlyMap,
		m.SocketStorageMap,
	)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	Getsockopt1 *ebpf.Program `ebpf:"getsockopt1"`
	Getsockopt2 *ebpf.Program `ebpf:"getsockopt2"`
	Setsockopt1 *ebpf.Program `ebpf:"setsockopt1"`
	Setsockopt2 *ebpf.Program `ebpf:"setsockopt2"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.Getsockopt1,
		p.Getsockopt2,
		p.Setsockopt1,
		p.Setsockopt2,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel.o
var _BpfBytes []byte
