// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Labels Set of labels
//
// swagger:model Labels
type Labels []string

// Validate validates this labels
func (m Labels) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this labels based on context it is used
func (m Labels) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
