apiVersion: batch.lx1036.kubebuilder/v1
kind: CronJob
metadata:
  name: cronjob-sample
spec:
  # Add fields here
  schedule: "*/1 * * * *"
  startingDeadlineSeconds: 60
  concurrencyPolicy: "Allow"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              args:
                - /bin/sh
                - -c
                - date; echo "Hello from the Kubernetes cluster"
          restartPolicy: OnFailure
