package labels

const (
    // LabelSourceUnspec is a label with unspecified source
    LabelSourceUnspec = "unspec"

    // LabelSourceAny is a label that matches any source
    LabelSourceAny = "any"

    // LabelSourceAnyKeyPrefix is prefix of a "any" label
    LabelSourceAnyKeyPrefix = LabelSourceAny + "."

    // LabelSourceK8s is a label imported from Kubernetes
    LabelSourceK8s = "k8s"

    // LabelSourceK8sKeyPrefix is prefix of a Kubernetes label
    LabelSourceK8sKeyPrefix = LabelSourceK8s + "."

    // LabelSourceContainer is a label imported from the container runtime
    LabelSourceContainer = "container"

    // LabelSourceReserved is the label source for reserved types.
    LabelSourceReserved = "reserved"

    // LabelSourceCIDR is the label source for generated CIDRs.
    LabelSourceCIDR = "cidr"

    // LabelSourceReservedKeyPrefix is the prefix of a reserved label
    LabelSourceReservedKeyPrefix = LabelSourceReserved + "."

    // LabelKeyFixedIdentity is the label that can be used to define a fixed
    // identity.
    LabelKeyFixedIdentity = "io.cilium.fixed-identity"

    // LabelSourceCiliumGenerated is for labels auto-generated by cilium without
    // user input
    LabelSourceCiliumGenerated = "cilium-generated"
)

// Label is the Cilium's representation of a container label.
type Label struct {
    Key   string `json:"key"`
    Value string `json:"value,omitempty"`
    // Source can be one of the above values (e.g.: LabelSourceContainer).
    //
    // +kubebuilder:validation:Optional
    Source string `json:"source"`
}

// Equals returns true if source, Key and Value are equal and false otherwise.
func (l *Label) Equals(b *Label) bool {
    if !l.IsAnySource() && l.Source != b.Source {
        return false
    }
    return l.Key == b.Key && l.Value == b.Value
}

// IsAnySource return if the label was set with source "any".
func (l *Label) IsAnySource() bool {
    return l.Source == LabelSourceAny
}

// Labels is a map of labels where the map's key is the same as the label's key.
type Labels map[string]Label
