kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: opdemo
subjects:
- kind: ServiceAccount
  name: opdemo
roleRef:
  kind: Role
  name: opdemo
  apiGroup: rbac.authorization.k8s.io
