






deepcopy-gen:
    # go get k8s.io/code-generator/cmd/deepcopy-gen
	deepcopy-gen -h "../apiserver/hack/boilerplate/boilerplate.go.txt" \
	-i "k8s-lx1036/k8s/scheduler/pkg/scheduler/apis/config" \
	--output-file-base zz_generated.deepcopy -o . -v 3
