[Log]
  Layout = "plain"

  [Log.Formats]
    log = "{{.Log}}|{{.Cluster}}"
    plain = ""

  # ip地址是伪造的
  [Log.Sources]
    [Log.Sources.shbt]
      Brokers = ["100.20.120.210:39092"]
    [Log.Sources.zzzc]
      Brokers = ["100.17.119.22:39092"]
    [Log.Sources.shyc]
      Brokers = ["100.20.120.210:39092"]
    [Log.Sources.zzdt]
      Brokers = ["100.17.119.22:39092"]
    [Log.Sources.all]
      Brokers = ["100.17.119.22:39092", "100.20.120.210:39092"]
