- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: update contents of index.html
  copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: 0755

- name: start nginx
  service:
    name: nginx
    state: started
