# packer build -var-file=./aws.json  ./packer.json
# sudo passwd ubuntu

- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: latest

    - name: Copy nginx config files
      copy:
        src: "./nginx/nginx.conf"
        dest: "/etc/nginx/nginx.conf"
        mode: 0644

    - name: Creates directory
      file:
        path: "/var/www/ubuntu"
        state: directory

    - name: Copy static files
      copy:
        src: "./nginx/web/"
        dest: "/var/www/ubuntu/"
        mode: 0644

    - name: Update static nginx config
      copy:
        src: "./nginx/conf.d/"
        dest: "/etc/nginx/conf.d/"
        mode: 0644

    - name: Enable Nginx
      service: name=nginx enabled=yes
      become: yes
