groups:
  - name: Redis集群监控
    rules:
      - alert: RedisDown
        expr: redis_up == 0
        for: 5m
        labels:
          severity: error
        annotations:
          summary: "Redis down (instance {{ $labels.realip }})"
          description: "Redis instance is down\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

      - alert: MissingBackup
        expr: time() - redis_rdb_last_save_timestamp_seconds > 60 * 60 * 24
        for: 5m
        labels:
          severity: error
        annotations:
          summary: "Missing backup (instance {{ $labels.realip }})"
          description: "Redis has not been backuped for 24 hours\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

      - alert: OutOfMemory
        expr: redis_memory_used_bytes / redis_total_system_memory_bytes * 100 > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Out of memory (instance {{ $labels.realip }})"
          description: "Redis is running out of memory (> 90%)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

      - alert: ReplicationBroken
        expr: delta(redis_connected_slaves[1m]) < 0
        for: 5m
        labels:
          severity: error
        annotations:
          summary: "Replication broken (instance {{ $labels.realip }})"
          description: "Redis instance lost a slave\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

      - alert: TooManyConnections
        expr: redis_connected_clients > 200
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Too many connections (instance {{ $labels.realip }})"
          description: "Redis instance has too many connections\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

      - alert: NotEnoughConnections
        expr: redis_connected_clients < 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Not enough connections (instance {{ $labels.realip }})"
          description: "Redis instance should have more connections (> 5)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

      - alert: RejectedConnections
        expr: increase(redis_rejected_connections_total[1m]) > 0
        for: 5m
        labels:
          severity: error
        annotations:
          summary: "Rejected connections (instance {{ $labels.realip }})"
          description: "Some connections to Redis has been rejected\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
