package converter

type Converter interface {
	// Converts kubernetes object to calico representation of it.
	Convert(k8sObj interface{}) (interface{}, error)
	
	// Returns appropriate key for the object
	GetKey(obj interface{}) string
	
	// DeleteArgsFromKey returns name and namespace of the object to pass to Delete
	// for the given key as generated by GetKey.
	DeleteArgsFromKey(key string) (string, string)
}
