-- MySQL Script generated by MySQL Workbench
-- Sun Jan 19 19:20:30 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema k8s_ui
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `api_key`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api_key` ;

CREATE TABLE IF NOT EXISTS `api_key` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL DEFAULT '',
  `token` LONGTEXT NOT NULL,
  `type` INT(11) NOT NULL DEFAULT 0,
  `resource_id` BIGINT(20) NULL DEFAULT NULL,
  `group_id` BIGINT(20) NULL DEFAULT NULL,
  `description` VARCHAR(512) NULL DEFAULT NULL,
  `user` VARCHAR(128) NOT NULL DEFAULT '',
  `expire_in` BIGINT(20) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `api_key_name` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `app`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app` ;

CREATE TABLE IF NOT EXISTS `app` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL DEFAULT '',
  `namespace_id` BIGINT(20) NOT NULL,
  `meta_data` LONGTEXT NOT NULL,
  `description` VARCHAR(512) NULL DEFAULT NULL,
  `user` VARCHAR(128) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `app_name` (`name` ASC),
  INDEX `app_namespace_id` (`namespace_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `app_starred`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_starred` ;

CREATE TABLE IF NOT EXISTS `app_starred` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `app_id` BIGINT(20) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `app_starred_app_id` (`app_id` ASC),
  INDEX `app_starred_user_id` (`user_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `app_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_user` ;

CREATE TABLE IF NOT EXISTS `app_user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `app_id` BIGINT(20) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  `group_id` BIGINT(20) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `app_user_app_id` (`app_id` ASC),
  INDEX `app_user_user_id` (`user_id` ASC),
  INDEX `app_user_group_id` (`group_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `audit_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `audit_log` ;

CREATE TABLE IF NOT EXISTS `audit_log` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `subject_id` BIGINT(20) NOT NULL DEFAULT 0,
  `log_type` VARCHAR(128) NOT NULL DEFAULT '',
  `log_level` VARCHAR(128) NOT NULL DEFAULT '',
  `action` VARCHAR(255) NOT NULL DEFAULT '',
  `message` LONGTEXT NULL DEFAULT NULL,
  `user_ip` VARCHAR(200) NOT NULL DEFAULT '',
  `user` VARCHAR(128) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `audit_log_log_type` (`log_type` ASC),
  INDEX `audit_log_log_level` (`log_level` ASC),
  INDEX `audit_log_action` (`action` ASC),
  INDEX `audit_log_user` (`user` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `charge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `charge` ;

CREATE TABLE IF NOT EXISTS `charge` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `namespace` VARCHAR(1024) NOT NULL DEFAULT '',
  `app` VARCHAR(128) NOT NULL DEFAULT '',
  `name` VARCHAR(1024) NOT NULL DEFAULT '',
  `type` VARCHAR(128) NOT NULL DEFAULT '',
  `unit_price` DECIMAL(12,4) NOT NULL DEFAULT '0.0000',
  `quantity` INT(11) NOT NULL DEFAULT 0,
  `amount` DECIMAL(12,4) NOT NULL DEFAULT '0.0000',
  `resource_name` VARCHAR(1024) NOT NULL DEFAULT '',
  `started_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `charge_app` (`app` ASC),
  INDEX `charge_type` (`type` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cluster`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cluster` ;

CREATE TABLE IF NOT EXISTS `cluster` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL DEFAULT '',
  `display_name` VARCHAR(512) NULL DEFAULT NULL,
  `meta_data` LONGTEXT NULL DEFAULT NULL,
  `master` VARCHAR(128) NOT NULL DEFAULT '',
  `kube_config` LONGTEXT NULL DEFAULT NULL,
  `description` VARCHAR(512) NULL DEFAULT NULL,
  `user` VARCHAR(128) NOT NULL DEFAULT '',
  `status` INT(11) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `config`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `config` ;

CREATE TABLE IF NOT EXISTS `config` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL DEFAULT '',
  `value` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `config_map`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `config_map` ;

CREATE TABLE IF NOT EXISTS `config_map` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL DEFAULT '',
  `meta_data` LONGTEXT NOT NULL,
  `app_id` BIGINT(20) NOT NULL,
  `description` VARCHAR(512) NULL DEFAULT NULL,
  `order_id` BIGINT(20) NOT NULL DEFAULT '0',
  `user` VARCHAR(128) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC),
  INDEX `config_map_app_id` (`app_id` ASC),
  INDEX `config_map_order_id` (`order_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `config_map_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `config_map_template` ;

CREATE TABLE IF NOT EXISTS `config_map_template` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL DEFAULT '',
  `template` LONGTEXT NOT NULL,
  `config_map_id` BIGINT(20) NOT NULL,
  `meta_data` LONGTEXT NOT NULL,
  `description` VARCHAR(512) NOT NULL DEFAULT '',
  `user` VARCHAR(128) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `config_map_template_config_map_id` (`config_map_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cronjob`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cronjob` ;

CREATE TABLE IF NOT EXISTS `cronjob` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL DEFAULT '',
  `meta_data` LONGTEXT NOT NULL,
  `app_id` BIGINT(20) NOT NULL,
  `description` VARCHAR(512) NULL DEFAULT NULL,
  `order_id` BIGINT(20) NOT NULL DEFAULT '0',
  `user` VARCHAR(128) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC),
  INDEX `cronjob_app_id` (`app_id` ASC),
  INDEX `cronjob_order_id` (`order_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cronjob_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cronjob_template` ;

CREATE TABLE IF NOT EXISTS `cronjob_template` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL DEFAULT '',
  `template` LONGTEXT NOT NULL,
  `cronjob_id` BIGINT(20) NOT NULL,
  `meta_data` LONGTEXT NOT NULL,
  `description` VARCHAR(512) NOT NULL DEFAULT '',
  `user` VARCHAR(128) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `cronjob_template_cronjob_id` (`cronjob_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `custom_link`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `custom_link` ;

CREATE TABLE IF NOT EXISTS `custom_link` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `namespace` VARCHAR(255) NOT NULL DEFAULT '',
  `link_type` VARCHAR(255) NOT NULL DEFAULT '',
  `url` VARCHAR(255) NOT NULL DEFAULT '',
  `add_param` TINYINT(1) NOT NULL DEFAULT '0',
  `params` VARCHAR(255) NULL DEFAULT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `custom_link_namespace` (`namespace` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `daemon_set`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daemon_set` ;

CREATE TABLE IF NOT EXISTS `daemon_set` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL DEFAULT '',
  `meta_data` LONGTEXT NOT NULL,
  `app_id` BIGINT(20) NOT NULL,
  `description` VARCHAR(512) NULL DEFAULT NULL,
  `order_id` BIGINT(20) NOT NULL DEFAULT 0,
  `user` VARCHAR(128) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC),
  INDEX `daemon_set_app_id` (`app_id` ASC),
  INDEX `daemon_set_order_id` (`order_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `daemon_set_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daemon_set_template` ;

CREATE TABLE IF NOT EXISTS `daemon_set_template` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL DEFAULT '',
  `template` LONGTEXT NOT NULL,
  `daemon_set_id` BIGINT(20) NOT NULL,
  `description` VARCHAR(512) NOT NULL DEFAULT '',
  `user` VARCHAR(128) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `daemon_set_template_daemon_set_id` (`daemon_set_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `deployment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `deployment` ;

CREATE TABLE IF NOT EXISTS `deployment` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL DEFAULT '',
  `meta_data` LONGTEXT NOT NULL,
  `app_id` BIGINT(20) NOT NULL,
  `description` VARCHAR(512) NULL DEFAULT NULL,
  `order_id` BIGINT(20) NOT NULL DEFAULT 0,
  `user` VARCHAR(128) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC),
  INDEX `deployment_app_id` (`app_id` ASC),
  INDEX `deployment_order_id` (`order_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `deployment_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `deployment_template` ;

CREATE TABLE IF NOT EXISTS `deployment_template` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL DEFAULT '',
  `template` LONGTEXT NOT NULL,
  `deployment_id` BIGINT(20) NOT NULL,
  `description` VARCHAR(512) NOT NULL DEFAULT '',
  `user` VARCHAR(128) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `deployment_template_deployment_id` (`deployment_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `group` ;

CREATE TABLE IF NOT EXISTS `group` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL DEFAULT '',
  `comment` LONGTEXT NOT NULL,
  `type` INT(11) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `group_name` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `group_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `group_permissions` ;

CREATE TABLE IF NOT EXISTS `group_permissions` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `group_id` BIGINT(20) NOT NULL,
  `permission_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 213
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hpa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hpa` ;

CREATE TABLE IF NOT EXISTS `hpa` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL DEFAULT '',
  `meta_data` LONGTEXT NOT NULL,
  `app_id` BIGINT(20) NOT NULL,
  `description` VARCHAR(255) NOT NULL DEFAULT '',
  `order_id` BIGINT(20) NOT NULL DEFAULT 0,
  `user` VARCHAR(128) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC),
  INDEX `hpa_app_id` (`app_id` ASC),
  INDEX `hpa_order_id` (`order_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hpa_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hpa_template` ;

CREATE TABLE IF NOT EXISTS `hpa_template` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL DEFAULT '',
  `template` LONGTEXT NOT NULL,
  `hpa_id` BIGINT(20) NOT NULL,
  `description` VARCHAR(512) NOT NULL DEFAULT '',
  `user` VARCHAR(128) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `hpa_template_hpa_id` (`hpa_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ingress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ingress` ;

CREATE TABLE IF NOT EXISTS `ingress` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL DEFAULT '',
  `meta_data` LONGTEXT NOT NULL,
  `app_id` BIGINT(20) NOT NULL,
  `description` VARCHAR(255) NOT NULL DEFAULT '',
  `order_id` BIGINT(20) NOT NULL DEFAULT 0,
  `user` VARCHAR(128) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC),
  INDEX `ingress_app_id` (`app_id` ASC),
  INDEX `ingress_order_id` (`order_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ingress_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ingress_template` ;

CREATE TABLE IF NOT EXISTS `ingress_template` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL DEFAULT '',
  `template` LONGTEXT NOT NULL,
  `ingress_id` BIGINT(20) NOT NULL,
  `description` VARCHAR(512) NOT NULL DEFAULT '',
  `user` VARCHAR(128) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `ingress_template_ingress_id` (`ingress_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invoice` ;

CREATE TABLE IF NOT EXISTS `invoice` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `namespace` VARCHAR(1024) NOT NULL DEFAULT '',
  `app` VARCHAR(128) NOT NULL DEFAULT '',
  `amount` DECIMAL(12,4) NOT NULL DEFAULT '0.0000',
  `ended_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `billed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `started_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `invoice_app` (`app` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `link_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `link_type` ;

CREATE TABLE IF NOT EXISTS `link_type` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(255) NOT NULL DEFAULT '',
  `display_name` VARCHAR(255) NOT NULL DEFAULT '',
  `default_url` VARCHAR(255) NOT NULL DEFAULT '',
  `param_list` VARCHAR(255) NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `type_name` (`type_name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `namespace`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `namespace` ;

CREATE TABLE IF NOT EXISTS `namespace` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL DEFAULT '',
  `kube_namespace` VARCHAR(128) NOT NULL DEFAULT '',
  `meta_data` LONGTEXT NOT NULL,
  `user` VARCHAR(128) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC),
  INDEX `namespace_kube_namespace` (`kube_namespace` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `namespace_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `namespace_user` ;

CREATE TABLE IF NOT EXISTS `namespace_user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `namespace_id` BIGINT(20) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  `group_id` BIGINT(20) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `namespace_user_namespace_id` (`namespace_id` ASC),
  INDEX `namespace_user_user_id` (`user_id` ASC),
  INDEX `namespace_user_group_id` (`group_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `notification` ;

CREATE TABLE IF NOT EXISTS `notification` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(128) NOT NULL DEFAULT '',
  `title` VARCHAR(2000) NOT NULL DEFAULT '',
  `message` LONGTEXT NOT NULL,
  `from_user_id` BIGINT(20) NOT NULL,
  `level` INT(11) NOT NULL DEFAULT '0',
  `is_published` TINYINT(1) NOT NULL DEFAULT '0',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `notification_type` (`type` ASC),
  INDEX `notification_from_user_id` (`from_user_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `notification_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `notification_log` ;

CREATE TABLE IF NOT EXISTS `notification_log` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL DEFAULT 0,
  `is_readed` TINYINT(1) NOT NULL DEFAULT 0,
  `notification_id` BIGINT(20) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `notification_log_notification_id` (`notification_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `permission` ;

CREATE TABLE IF NOT EXISTS `permission` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL DEFAULT '',
  `comment` LONGTEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `permission_name` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 228
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `persistent_volume_claim`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `persistent_volume_claim` ;

CREATE TABLE IF NOT EXISTS `persistent_volume_claim` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL DEFAULT '',
  `meta_data` LONGTEXT NOT NULL,
  `app_id` BIGINT(20) NOT NULL,
  `description` VARCHAR(512) NULL DEFAULT NULL,
  `order_id` BIGINT(20) NOT NULL DEFAULT '0',
  `user` VARCHAR(128) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC),
  INDEX `persistent_volume_claim_app_id` (`app_id` ASC),
  INDEX `persistent_volume_claim_order_id` (`order_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `persistent_volume_claim_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `persistent_volume_claim_template` ;

CREATE TABLE IF NOT EXISTS `persistent_volume_claim_template` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL DEFAULT '',
  `template` LONGTEXT NOT NULL,
  `persistent_volume_claim_id` BIGINT(20) NOT NULL,
  `meta_data` LONGTEXT NOT NULL,
  `description` VARCHAR(512) NOT NULL DEFAULT '',
  `user` VARCHAR(128) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `persistent_volume_claim_template_persistent_volume_claim_id` (`persistent_volume_claim_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `publish_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `publish_history` ;

CREATE TABLE IF NOT EXISTS `publish_history` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `type` INT(11) NOT NULL DEFAULT '0',
  `resource_id` BIGINT(20) NOT NULL DEFAULT '0',
  `resource_name` VARCHAR(128) NOT NULL DEFAULT '',
  `template_id` BIGINT(20) NOT NULL DEFAULT '0',
  `cluster` VARCHAR(128) NOT NULL DEFAULT '',
  `status` INT(11) NOT NULL DEFAULT '0',
  `message` LONGTEXT NOT NULL,
  `user` VARCHAR(128) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `publish_history_type` (`type` ASC),
  INDEX `publish_history_resource_id` (`resource_id` ASC),
  INDEX `publish_history_template_id` (`template_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `publish_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `publish_status` ;

CREATE TABLE IF NOT EXISTS `publish_status` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `type` INT(11) NOT NULL DEFAULT 0,
  `resource_id` BIGINT(20) NOT NULL DEFAULT 0,
  `template_id` BIGINT(20) NOT NULL DEFAULT 0,
  `cluster` VARCHAR(128) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  INDEX `publish_status_type` (`type` ASC),
  INDEX `publish_status_resource_id` (`resource_id` ASC),
  INDEX `publish_status_template_id` (`template_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `secret`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `secret` ;

CREATE TABLE IF NOT EXISTS `secret` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL DEFAULT '',
  `meta_data` LONGTEXT NOT NULL,
  `app_id` BIGINT(20) NOT NULL,
  `description` VARCHAR(512) NULL DEFAULT NULL,
  `order_id` BIGINT(20) NOT NULL DEFAULT '0',
  `user` VARCHAR(128) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC),
  INDEX `secret_app_id` (`app_id` ASC),
  INDEX `secret_order_id` (`order_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `secret_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `secret_template` ;

CREATE TABLE IF NOT EXISTS `secret_template` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL DEFAULT '',
  `template` LONGTEXT NOT NULL,
  `secret_map_id` BIGINT(20) NOT NULL,
  `meta_data` LONGTEXT NOT NULL,
  `user` VARCHAR(128) NOT NULL DEFAULT '',
  `description` VARCHAR(512) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `secret_template_secret_map_id` (`secret_map_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `service` ;

CREATE TABLE IF NOT EXISTS `service` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL DEFAULT '',
  `meta_data` LONGTEXT NOT NULL,
  `app_id` BIGINT(20) NOT NULL,
  `description` VARCHAR(512) NULL DEFAULT NULL,
  `order_id` BIGINT(20) NOT NULL DEFAULT 0,
  `user` VARCHAR(128) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC),
  INDEX `service_app_id` (`app_id` ASC),
  INDEX `service_order_id` (`order_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `service_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `service_template` ;

CREATE TABLE IF NOT EXISTS `service_template` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL DEFAULT '',
  `template` LONGTEXT NOT NULL,
  `service_id` BIGINT(20) NOT NULL,
  `user` VARCHAR(128) NOT NULL DEFAULT '',
  `description` VARCHAR(512) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `service_template_service_id` (`service_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `statefulset`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statefulset` ;

CREATE TABLE IF NOT EXISTS `statefulset` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL DEFAULT '',
  `meta_data` LONGTEXT NOT NULL,
  `app_id` BIGINT(20) NOT NULL,
  `description` VARCHAR(512) NULL DEFAULT NULL,
  `order_id` BIGINT(20) NOT NULL DEFAULT 0,
  `user` VARCHAR(128) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC),
  INDEX `statefulset_app_id` (`app_id` ASC),
  INDEX `statefulset_order_id` (`order_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `statefulset_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statefulset_template` ;

CREATE TABLE IF NOT EXISTS `statefulset_template` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL DEFAULT '',
  `template` LONGTEXT NOT NULL,
  `statefulset_id` BIGINT(20) NOT NULL,
  `description` VARCHAR(512) NOT NULL DEFAULT '',
  `user` VARCHAR(128) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `statefulset_template_statefulset_id` (`statefulset_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL DEFAULT '',
  `password` VARCHAR(255) NOT NULL DEFAULT '',
  `salt` VARCHAR(32) NOT NULL DEFAULT '',
  `email` VARCHAR(200) NOT NULL DEFAULT '',
  `display` VARCHAR(200) NOT NULL DEFAULT '',
  `comment` LONGTEXT NOT NULL,
  `type` INT(11) NOT NULL DEFAULT 0,
  `admin` TINYINT(1) NOT NULL DEFAULT 0,
  `last_login` DATETIME NOT NULL,
  `last_ip` VARCHAR(200) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `web_hook`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `web_hook` ;

CREATE TABLE IF NOT EXISTS `web_hook` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL DEFAULT '',
  `scope` BIGINT(20) NOT NULL DEFAULT '0',
  `object_id` BIGINT(20) NOT NULL DEFAULT '0',
  `url` VARCHAR(512) NULL DEFAULT NULL,
  `secret` VARCHAR(512) NULL DEFAULT NULL,
  `events` LONGTEXT NOT NULL,
  `user` VARCHAR(128) NOT NULL DEFAULT '',
  `enabled` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `web_hook_name` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
