version: '3.6'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  portainer:
    build:
      context: ""
    volumes:
      - ${DATA_PATH_HOST}/portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${PORTAINER_PORT}:9000
    networks:
      - backend

